version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    groups:
      gh-actions-security-updates:
        applies-to: security-updates
        patterns:
          - '*'
      gh-actions-updates:
        applies-to: version-updates
        patterns:
          - '*'
