// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-permissions-api/models"
	"github.com/ONSdigital/dp-permissions-api/permissions"
	"sync"
)

// Ensure, that StoreMock does implement permissions.Store.
// If this is not the case, regenerate this file with moq.
var _ permissions.Store = &StoreMock{}

// StoreMock is a mock implementation of permissions.Store.
//
//     func TestSomethingThatUsesStore(t *testing.T) {
//
//         // make and configure a mocked permissions.Store
//         mockedStore := &StoreMock{
//             GetAllPoliciesFunc: func(ctx context.Context) ([]*models.Policy, error) {
// 	               panic("mock out the GetAllPolicies method")
//             },
//             GetAllRolesFunc: func(ctx context.Context) ([]*models.Role, error) {
// 	               panic("mock out the GetAllRoles method")
//             },
//         }
//
//         // use mockedStore in code that requires permissions.Store
//         // and then make assertions.
//
//     }
type StoreMock struct {
	// GetAllPoliciesFunc mocks the GetAllPolicies method.
	GetAllPoliciesFunc func(ctx context.Context) ([]*models.Policy, error)

	// GetAllRolesFunc mocks the GetAllRoles method.
	GetAllRolesFunc func(ctx context.Context) ([]*models.Role, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetAllPolicies holds details about calls to the GetAllPolicies method.
		GetAllPolicies []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetAllRoles holds details about calls to the GetAllRoles method.
		GetAllRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGetAllPolicies sync.RWMutex
	lockGetAllRoles    sync.RWMutex
}

// GetAllPolicies calls GetAllPoliciesFunc.
func (mock *StoreMock) GetAllPolicies(ctx context.Context) ([]*models.Policy, error) {
	if mock.GetAllPoliciesFunc == nil {
		panic("StoreMock.GetAllPoliciesFunc: method is nil but Store.GetAllPolicies was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAllPolicies.Lock()
	mock.calls.GetAllPolicies = append(mock.calls.GetAllPolicies, callInfo)
	mock.lockGetAllPolicies.Unlock()
	return mock.GetAllPoliciesFunc(ctx)
}

// GetAllPoliciesCalls gets all the calls that were made to GetAllPolicies.
// Check the length with:
//     len(mockedStore.GetAllPoliciesCalls())
func (mock *StoreMock) GetAllPoliciesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAllPolicies.RLock()
	calls = mock.calls.GetAllPolicies
	mock.lockGetAllPolicies.RUnlock()
	return calls
}

// GetAllRoles calls GetAllRolesFunc.
func (mock *StoreMock) GetAllRoles(ctx context.Context) ([]*models.Role, error) {
	if mock.GetAllRolesFunc == nil {
		panic("StoreMock.GetAllRolesFunc: method is nil but Store.GetAllRoles was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAllRoles.Lock()
	mock.calls.GetAllRoles = append(mock.calls.GetAllRoles, callInfo)
	mock.lockGetAllRoles.Unlock()
	return mock.GetAllRolesFunc(ctx)
}

// GetAllRolesCalls gets all the calls that were made to GetAllRoles.
// Check the length with:
//     len(mockedStore.GetAllRolesCalls())
func (mock *StoreMock) GetAllRolesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAllRoles.RLock()
	calls = mock.calls.GetAllRoles
	mock.lockGetAllRoles.RUnlock()
	return calls
}
