// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/ONSdigital/dp-permissions-api/models"
	"github.com/ONSdigital/dp-permissions-api/sdk"
	"sync"
)

// Ensure, that ClienterMock does implement sdk.Clienter.
// If this is not the case, regenerate this file with moq.
var _ sdk.Clienter = &ClienterMock{}

// ClienterMock is a mock implementation of sdk.Clienter.
//
//	func TestSomethingThatUsesClienter(t *testing.T) {
//
//		// make and configure a mocked sdk.Clienter
//		mockedClienter := &ClienterMock{
//			DeletePolicyFunc: func(ctx context.Context, id string) error {
//				panic("mock out the DeletePolicy method")
//			},
//			GetPermissionsBundleFunc: func(ctx context.Context) (sdk.Bundle, error) {
//				panic("mock out the GetPermissionsBundle method")
//			},
//			GetPolicyFunc: func(ctx context.Context, id string) (*models.Policy, error) {
//				panic("mock out the GetPolicy method")
//			},
//			GetRoleFunc: func(ctx context.Context, id string) (*models.Roles, error) {
//				panic("mock out the GetRole method")
//			},
//			GetRolesFunc: func(ctx context.Context) (*models.Roles, error) {
//				panic("mock out the GetRoles method")
//			},
//			PostPolicyFunc: func(ctx context.Context, policy models.PolicyInfo) (*models.Policy, error) {
//				panic("mock out the PostPolicy method")
//			},
//			PostPolicyWithIDFunc: func(ctx context.Context, headers sdk.Headers, id string, policy models.PolicyInfo) (*models.Policy, error) {
//				panic("mock out the PostPolicyWithID method")
//			},
//			PutPolicyFunc: func(ctx context.Context, id string, policy models.Policy) error {
//				panic("mock out the PutPolicy method")
//			},
//		}
//
//		// use mockedClienter in code that requires sdk.Clienter
//		// and then make assertions.
//
//	}
type ClienterMock struct {
	// DeletePolicyFunc mocks the DeletePolicy method.
	DeletePolicyFunc func(ctx context.Context, id string) error

	// GetPermissionsBundleFunc mocks the GetPermissionsBundle method.
	GetPermissionsBundleFunc func(ctx context.Context) (sdk.Bundle, error)

	// GetPolicyFunc mocks the GetPolicy method.
	GetPolicyFunc func(ctx context.Context, id string) (*models.Policy, error)

	// GetRoleFunc mocks the GetRole method.
	GetRoleFunc func(ctx context.Context, id string) (*models.Roles, error)

	// GetRolesFunc mocks the GetRoles method.
	GetRolesFunc func(ctx context.Context) (*models.Roles, error)

	// PostPolicyFunc mocks the PostPolicy method.
	PostPolicyFunc func(ctx context.Context, policy models.PolicyInfo) (*models.Policy, error)

	// PostPolicyWithIDFunc mocks the PostPolicyWithID method.
	PostPolicyWithIDFunc func(ctx context.Context, headers sdk.Headers, id string, policy models.PolicyInfo) (*models.Policy, error)

	// PutPolicyFunc mocks the PutPolicy method.
	PutPolicyFunc func(ctx context.Context, id string, policy models.Policy) error

	// calls tracks calls to the methods.
	calls struct {
		// DeletePolicy holds details about calls to the DeletePolicy method.
		DeletePolicy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetPermissionsBundle holds details about calls to the GetPermissionsBundle method.
		GetPermissionsBundle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetPolicy holds details about calls to the GetPolicy method.
		GetPolicy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetRole holds details about calls to the GetRole method.
		GetRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetRoles holds details about calls to the GetRoles method.
		GetRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// PostPolicy holds details about calls to the PostPolicy method.
		PostPolicy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Policy is the policy argument value.
			Policy models.PolicyInfo
		}
		// PostPolicyWithID holds details about calls to the PostPolicyWithID method.
		PostPolicyWithID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Headers is the headers argument value.
			Headers sdk.Headers
			// ID is the id argument value.
			ID string
			// Policy is the policy argument value.
			Policy models.PolicyInfo
		}
		// PutPolicy holds details about calls to the PutPolicy method.
		PutPolicy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Policy is the policy argument value.
			Policy models.Policy
		}
	}
	lockDeletePolicy         sync.RWMutex
	lockGetPermissionsBundle sync.RWMutex
	lockGetPolicy            sync.RWMutex
	lockGetRole              sync.RWMutex
	lockGetRoles             sync.RWMutex
	lockPostPolicy           sync.RWMutex
	lockPostPolicyWithID     sync.RWMutex
	lockPutPolicy            sync.RWMutex
}

// DeletePolicy calls DeletePolicyFunc.
func (mock *ClienterMock) DeletePolicy(ctx context.Context, id string) error {
	if mock.DeletePolicyFunc == nil {
		panic("ClienterMock.DeletePolicyFunc: method is nil but Clienter.DeletePolicy was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeletePolicy.Lock()
	mock.calls.DeletePolicy = append(mock.calls.DeletePolicy, callInfo)
	mock.lockDeletePolicy.Unlock()
	return mock.DeletePolicyFunc(ctx, id)
}

// DeletePolicyCalls gets all the calls that were made to DeletePolicy.
// Check the length with:
//
//	len(mockedClienter.DeletePolicyCalls())
func (mock *ClienterMock) DeletePolicyCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDeletePolicy.RLock()
	calls = mock.calls.DeletePolicy
	mock.lockDeletePolicy.RUnlock()
	return calls
}

// GetPermissionsBundle calls GetPermissionsBundleFunc.
func (mock *ClienterMock) GetPermissionsBundle(ctx context.Context) (sdk.Bundle, error) {
	if mock.GetPermissionsBundleFunc == nil {
		panic("ClienterMock.GetPermissionsBundleFunc: method is nil but Clienter.GetPermissionsBundle was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetPermissionsBundle.Lock()
	mock.calls.GetPermissionsBundle = append(mock.calls.GetPermissionsBundle, callInfo)
	mock.lockGetPermissionsBundle.Unlock()
	return mock.GetPermissionsBundleFunc(ctx)
}

// GetPermissionsBundleCalls gets all the calls that were made to GetPermissionsBundle.
// Check the length with:
//
//	len(mockedClienter.GetPermissionsBundleCalls())
func (mock *ClienterMock) GetPermissionsBundleCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetPermissionsBundle.RLock()
	calls = mock.calls.GetPermissionsBundle
	mock.lockGetPermissionsBundle.RUnlock()
	return calls
}

// GetPolicy calls GetPolicyFunc.
func (mock *ClienterMock) GetPolicy(ctx context.Context, id string) (*models.Policy, error) {
	if mock.GetPolicyFunc == nil {
		panic("ClienterMock.GetPolicyFunc: method is nil but Clienter.GetPolicy was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetPolicy.Lock()
	mock.calls.GetPolicy = append(mock.calls.GetPolicy, callInfo)
	mock.lockGetPolicy.Unlock()
	return mock.GetPolicyFunc(ctx, id)
}

// GetPolicyCalls gets all the calls that were made to GetPolicy.
// Check the length with:
//
//	len(mockedClienter.GetPolicyCalls())
func (mock *ClienterMock) GetPolicyCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetPolicy.RLock()
	calls = mock.calls.GetPolicy
	mock.lockGetPolicy.RUnlock()
	return calls
}

// GetRole calls GetRoleFunc.
func (mock *ClienterMock) GetRole(ctx context.Context, id string) (*models.Roles, error) {
	if mock.GetRoleFunc == nil {
		panic("ClienterMock.GetRoleFunc: method is nil but Clienter.GetRole was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetRole.Lock()
	mock.calls.GetRole = append(mock.calls.GetRole, callInfo)
	mock.lockGetRole.Unlock()
	return mock.GetRoleFunc(ctx, id)
}

// GetRoleCalls gets all the calls that were made to GetRole.
// Check the length with:
//
//	len(mockedClienter.GetRoleCalls())
func (mock *ClienterMock) GetRoleCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetRole.RLock()
	calls = mock.calls.GetRole
	mock.lockGetRole.RUnlock()
	return calls
}

// GetRoles calls GetRolesFunc.
func (mock *ClienterMock) GetRoles(ctx context.Context) (*models.Roles, error) {
	if mock.GetRolesFunc == nil {
		panic("ClienterMock.GetRolesFunc: method is nil but Clienter.GetRoles was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetRoles.Lock()
	mock.calls.GetRoles = append(mock.calls.GetRoles, callInfo)
	mock.lockGetRoles.Unlock()
	return mock.GetRolesFunc(ctx)
}

// GetRolesCalls gets all the calls that were made to GetRoles.
// Check the length with:
//
//	len(mockedClienter.GetRolesCalls())
func (mock *ClienterMock) GetRolesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetRoles.RLock()
	calls = mock.calls.GetRoles
	mock.lockGetRoles.RUnlock()
	return calls
}

// PostPolicy calls PostPolicyFunc.
func (mock *ClienterMock) PostPolicy(ctx context.Context, policy models.PolicyInfo) (*models.Policy, error) {
	if mock.PostPolicyFunc == nil {
		panic("ClienterMock.PostPolicyFunc: method is nil but Clienter.PostPolicy was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Policy models.PolicyInfo
	}{
		Ctx:    ctx,
		Policy: policy,
	}
	mock.lockPostPolicy.Lock()
	mock.calls.PostPolicy = append(mock.calls.PostPolicy, callInfo)
	mock.lockPostPolicy.Unlock()
	return mock.PostPolicyFunc(ctx, policy)
}

// PostPolicyCalls gets all the calls that were made to PostPolicy.
// Check the length with:
//
//	len(mockedClienter.PostPolicyCalls())
func (mock *ClienterMock) PostPolicyCalls() []struct {
	Ctx    context.Context
	Policy models.PolicyInfo
} {
	var calls []struct {
		Ctx    context.Context
		Policy models.PolicyInfo
	}
	mock.lockPostPolicy.RLock()
	calls = mock.calls.PostPolicy
	mock.lockPostPolicy.RUnlock()
	return calls
}

// PostPolicyWithID calls PostPolicyWithIDFunc.
func (mock *ClienterMock) PostPolicyWithID(ctx context.Context, headers sdk.Headers, id string, policy models.PolicyInfo) (*models.Policy, error) {
	if mock.PostPolicyWithIDFunc == nil {
		panic("ClienterMock.PostPolicyWithIDFunc: method is nil but Clienter.PostPolicyWithID was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Headers sdk.Headers
		ID      string
		Policy  models.PolicyInfo
	}{
		Ctx:     ctx,
		Headers: headers,
		ID:      id,
		Policy:  policy,
	}
	mock.lockPostPolicyWithID.Lock()
	mock.calls.PostPolicyWithID = append(mock.calls.PostPolicyWithID, callInfo)
	mock.lockPostPolicyWithID.Unlock()
	return mock.PostPolicyWithIDFunc(ctx, headers, id, policy)
}

// PostPolicyWithIDCalls gets all the calls that were made to PostPolicyWithID.
// Check the length with:
//
//	len(mockedClienter.PostPolicyWithIDCalls())
func (mock *ClienterMock) PostPolicyWithIDCalls() []struct {
	Ctx     context.Context
	Headers sdk.Headers
	ID      string
	Policy  models.PolicyInfo
} {
	var calls []struct {
		Ctx     context.Context
		Headers sdk.Headers
		ID      string
		Policy  models.PolicyInfo
	}
	mock.lockPostPolicyWithID.RLock()
	calls = mock.calls.PostPolicyWithID
	mock.lockPostPolicyWithID.RUnlock()
	return calls
}

// PutPolicy calls PutPolicyFunc.
func (mock *ClienterMock) PutPolicy(ctx context.Context, id string, policy models.Policy) error {
	if mock.PutPolicyFunc == nil {
		panic("ClienterMock.PutPolicyFunc: method is nil but Clienter.PutPolicy was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     string
		Policy models.Policy
	}{
		Ctx:    ctx,
		ID:     id,
		Policy: policy,
	}
	mock.lockPutPolicy.Lock()
	mock.calls.PutPolicy = append(mock.calls.PutPolicy, callInfo)
	mock.lockPutPolicy.Unlock()
	return mock.PutPolicyFunc(ctx, id, policy)
}

// PutPolicyCalls gets all the calls that were made to PutPolicy.
// Check the length with:
//
//	len(mockedClienter.PutPolicyCalls())
func (mock *ClienterMock) PutPolicyCalls() []struct {
	Ctx    context.Context
	ID     string
	Policy models.Policy
} {
	var calls []struct {
		Ctx    context.Context
		ID     string
		Policy models.Policy
	}
	mock.lockPutPolicy.RLock()
	calls = mock.calls.PutPolicy
	mock.lockPutPolicy.RUnlock()
	return calls
}
