// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"github.com/ONSdigital/dp-permissions-api/api"
	"github.com/ONSdigital/dp-permissions-api/models"
	"sync"
)

// Ensure, that PermissionsStoreMock does implement api.PermissionsStore.
// If this is not the case, regenerate this file with moq.
var _ api.PermissionsStore = &PermissionsStoreMock{}

// PermissionsStoreMock is a mock implementation of api.PermissionsStore.
//
//     func TestSomethingThatUsesPermissionsStore(t *testing.T) {
//
//         // make and configure a mocked api.PermissionsStore
//         mockedPermissionsStore := &PermissionsStoreMock{
//             CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
// 	               panic("mock out the Checker method")
//             },
//             CloseFunc: func(ctx context.Context) error {
// 	               panic("mock out the Close method")
//             },
//             GetRoleFunc: func(ctx context.Context, id string) (*models.Role, error) {
// 	               panic("mock out the GetRole method")
//             },
//             GetRolesFunc: func(ctx context.Context, offset int, limit int) (*models.Roles, error) {
// 	               panic("mock out the GetRoles method")
//             },
//         }
//
//         // use mockedPermissionsStore in code that requires api.PermissionsStore
//         // and then make assertions.
//
//     }
type PermissionsStoreMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// CloseFunc mocks the Close method.
	CloseFunc func(ctx context.Context) error

	// GetRoleFunc mocks the GetRole method.
	GetRoleFunc func(ctx context.Context, id string) (*models.Role, error)

	// GetRolesFunc mocks the GetRoles method.
	GetRolesFunc func(ctx context.Context, offset int, limit int) (*models.Roles, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
		// Close holds details about calls to the Close method.
		Close []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetRole holds details about calls to the GetRole method.
		GetRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetRoles holds details about calls to the GetRoles method.
		GetRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Offset is the offset argument value.
			Offset int
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockChecker  sync.RWMutex
	lockClose    sync.RWMutex
	lockGetRole  sync.RWMutex
	lockGetRoles sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *PermissionsStoreMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("PermissionsStoreMock.CheckerFunc: method is nil but PermissionsStore.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//     len(mockedPermissionsStore.CheckerCalls())
func (mock *PermissionsStoreMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *PermissionsStoreMock) Close(ctx context.Context) error {
	if mock.CloseFunc == nil {
		panic("PermissionsStoreMock.CloseFunc: method is nil but PermissionsStore.Close was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc(ctx)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//     len(mockedPermissionsStore.CloseCalls())
func (mock *PermissionsStoreMock) CloseCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// GetRole calls GetRoleFunc.
func (mock *PermissionsStoreMock) GetRole(ctx context.Context, id string) (*models.Role, error) {
	if mock.GetRoleFunc == nil {
		panic("PermissionsStoreMock.GetRoleFunc: method is nil but PermissionsStore.GetRole was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetRole.Lock()
	mock.calls.GetRole = append(mock.calls.GetRole, callInfo)
	mock.lockGetRole.Unlock()
	return mock.GetRoleFunc(ctx, id)
}

// GetRoleCalls gets all the calls that were made to GetRole.
// Check the length with:
//     len(mockedPermissionsStore.GetRoleCalls())
func (mock *PermissionsStoreMock) GetRoleCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetRole.RLock()
	calls = mock.calls.GetRole
	mock.lockGetRole.RUnlock()
	return calls
}

// GetRoles calls GetRolesFunc.
func (mock *PermissionsStoreMock) GetRoles(ctx context.Context, offset int, limit int) (*models.Roles, error) {
	if mock.GetRolesFunc == nil {
		panic("PermissionsStoreMock.GetRolesFunc: method is nil but PermissionsStore.GetRoles was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Offset int
		Limit  int
	}{
		Ctx:    ctx,
		Offset: offset,
		Limit:  limit,
	}
	mock.lockGetRoles.Lock()
	mock.calls.GetRoles = append(mock.calls.GetRoles, callInfo)
	mock.lockGetRoles.Unlock()
	return mock.GetRolesFunc(ctx, offset, limit)
}

// GetRolesCalls gets all the calls that were made to GetRoles.
// Check the length with:
//     len(mockedPermissionsStore.GetRolesCalls())
func (mock *PermissionsStoreMock) GetRolesCalls() []struct {
	Ctx    context.Context
	Offset int
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		Offset int
		Limit  int
	}
	mock.lockGetRoles.RLock()
	calls = mock.calls.GetRoles
	mock.lockGetRoles.RUnlock()
	return calls
}
